//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.Application.App
{
    using DCEM.UserCenterService.Main.Application.App.Contrac;
    using DCEM.UserCenterService.Main.Application.Services.Contrac;
    using DCEM.UserCenterService.Main.ViewModel.Request;
    using DCEM.UserCenterService.Main.ViewModel.Response;
    using System.Threading.Tasks;
    using MSLibrary.Xrm;
    using MSLibrary;
    using System.Collections.Generic;
    using System;

    public interface IAppUser
    {

        void IntegralCreate(string key, string userid);
        Task<ValidateResult> ValUserSecurityquestion(UserLoginRequest req);
        Task<ValidateResult<CrmEntity>> GetAgreement(string id);
        Task<ValidateResult<CrmEntity>> LoginAccount(UserLoginRequest request);

        Task<ValidateResult<CrmEntity>> GetUser(UserLoginRequest request);

        Task<ValidateResult> AddUser(UserAddRequest request);

        Task<ValidateResult> UpdateUser(UserAddRequest request);

        Task<ValidateResult<List<CrmEntity>>> GetSecurityquestion();

        void LoginLog(UserLoginRequest model, Guid userid, int type); 

        Task<ValidateResult> UpdateUserPwd(UserLoginRequest model);

        Task<UserTagListResponse> getusertag(UserDetailRequest userDetailRequest);
        Task<UserScoreListResponse> getuserscore(UserDetailRequest userDetailRequest);
        Task<ValidateResult> DeDucationIntegral(UserDeDucationIntegralRequest request);


        Task<CrmEntity> getuserdetail(UserDetailRequest userDetailRequest);
        /// <summary>
        /// 获取用户通知信息
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        Task<QueryResult<CrmEntity>> QueryUserNotices(UserNoticeRequest request);
        /// <summary>
        /// 更新用户通知阅读状态
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        Task<bool> UpdateUserNoticeReadStatus(UserNoticeRequest request);
        /// <summary>
        /// 获取用户通知信息未阅读数量
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        Task<int> GetUserNoticesNoReadCount(string userid);
    }
}
