//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.Application.App.Contrac
{
    using DCEM.UserCenterService.Main.Application.App.Contrac;
    using DCEM.UserCenterService.Main.Application.Services.Contrac;
    using DCEM.UserCenterService.Main.ViewModel.Request;
    using DCEM.UserCenterService.Main.ViewModel.Response;
    using System.Threading.Tasks;
    using MSLibrary.Xrm;
    using MSLibrary;

    public interface IAppSmallBooking
    {
        /// <summary>
        /// 小订订单活动查询接口（小订活动、小订权益包、小订权益项、小订选配）
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        Task<SmallBookingListResponse> QuerySmallBooking(SmallBookingListRequest request);
        /// <summary>
        /// 小订订单创建、支付、退款申请、退订
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        Task<ValidateResult<CrmEntity>> AddOrEdit(SmallBookingRequest request);

        /// <summary>
        /// 小订订单查询接口
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        Task<QueryResult<CrmEntity>> QuerySmallOrder(SmallOrderListRequest request);
    }
}
