//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.Application.Services
{
    using DCEM.UserCenterService.Main.Application.Repository.Contrac;
    using DCEM.UserCenterService.Main.Application.Services.Contrac;
    using DCEM.UserCenterService.Main.ViewModel.Request;
    using DCEM.UserCenterService.Main.ViewModel.Response;
    using System.Threading.Tasks;
    using MSLibrary.Xrm;
    using System;
    using DCEM.UserCenterService.Main.Common;
    using System.Xml.Linq;
    using static DCEM.UserCenterService.Main.Common.UserEnum;

    public class ContentManagementService : IContentManagementService
    {
        
        private ICrmService _crmService;
        
        public IContentManagementRepository _contentmanagementRepository;
        
        public ContentManagementService(ICrmService crmService, IContentManagementRepository contentmanagementRepository)
        {
             _crmService = crmService;
                     _contentmanagementRepository=contentmanagementRepository;
        }

        public async Task<ContentListResponse> GetList(ContentListRequest contentListRequest)
        {
            try
            {
                var response = new ContentListResponse() { };
                var entities = await GetEntities(contentListRequest);
                response.ContentList = entities.Results;
                response.ALLTotalCount = entities.Count;
                response.PageSize = contentListRequest.PageSize;
                response.CurrentPage = contentListRequest.PageIndex;
                return response;
            }
            catch (Exception ex)
            {
                return new ContentListResponse() { ErrorMessage = ex.Message + ";" + ex.InnerException?.Message };
            }
        }

        private async Task<CrmEntityCollection> GetEntities(ContentListRequest contentListRequest)
        {
            var crmRequestHelper = new CrmRequestHelper();
            XDocument fetchXdoc = null;
            string entityName = string.Empty;

            switch (contentListRequest.Type)
            {
                case ContentType.Activity:
                    fetchXdoc = await _contentmanagementRepository.GetActivityListFetchXml(contentListRequest);
                    entityName = "mcs_activitycontents";
                    break;
                case ContentType.Front:
                    fetchXdoc = await _contentmanagementRepository.GetFrontListFetchXml(contentListRequest);
                    entityName = "mcs_frontcontent";
                    break;
                case ContentType.News:
                    fetchXdoc = await _contentmanagementRepository.GetNewsListFetchXml(contentListRequest);
                    entityName = "mcs_newscontents";
                    break;
            }
            return await crmRequestHelper.ExecuteAsync(_crmService, entityName, fetchXdoc);
        }

        public async Task<ContentDetailResponse> GetDetail(ContentDetailRequest contentDetailRequest)
        {
            try
            {
                var response = new ContentDetailResponse() { };
                response.Content = await GetEntity(contentDetailRequest);
                return response;
            }
            catch (Exception ex)
            {
                return new ContentDetailResponse() { ErrorMessage = ex.Message + ";" + ex.InnerException?.Message };
            }
        }

        private async Task<CrmEntity> GetEntity(ContentDetailRequest contentDetailRequest)
        {
            var crmRequestHelper = new CrmRequestHelper();
            string entityName = string.Empty;

            switch (contentDetailRequest.Type)
            {
                case ContentType.Activity:
                    entityName = "mcs_activitycontents";
                    break;
                case ContentType.Front:
                    entityName = "mcs_frontcontent";
                    break;
                case ContentType.News:
                    entityName = "mcs_newscontents";
                    break;
            }
            return await crmRequestHelper.Retrieve(_crmService, entityName, contentDetailRequest.Id);
        }
    }
}
