//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.ViewModel.Request
{
    using System.Collections.Generic;
    using MSLibrary.Xrm;
    
    
    public class BlindOrderListRequest : PageBaseRequestModel
    {
        /// <summary>
        /// 手机号
        /// </summary>
        public string mcs_mobilephone { get; set; }

        /// <summary>
        /// 预约号状态（0：未下单，1：已下单）
        /// </summary>
        public int? mcs_premiumcodestatus { get; set; }


    }
}
