//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.ViewModel.Request
{
    using System;
    using System.Collections.Generic;
    using MSLibrary.Xrm;
    
    
    public class SmallBookingListRequest : PageBaseRequestModel
    {
        /// <summary>
        /// 开始时间	
        /// </summary>
        public DateTime? mcs_starttime { get; set; }
        /// <summary>
        /// 结束时间	
        /// </summary>
        public DateTime? mcs_endtime { get; set; }
        /// <summary>
        /// 发布状态（上架、下架）
        /// </summary>
        public int? mcs_poststatus{ get; set; }
    }
}
