//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.ViewModel.Request
{
    using System.Collections.Generic;
    using MSLibrary.Xrm;
    
    
    public class UserCarInfoListRequest : PageBaseRequestModel
    {
        /// <summary>
        /// 车主姓名
        /// </summary>
        public string mcs_username { get; set; }

        /// <summary>
        /// 手机号
        /// </summary>
        public string mcs_phone { get; set; }

        /// <summary>
        /// 车牌号
        /// </summary>
        public string mcs_plate { get; set; }

        /// <summary>
        /// 关联车辆档案
        /// </summary>
        public string mcs_carinfoid { get; set; }


        public string mcs_userid { get; set; }
    }
}
