//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.Application.Repository.Contrac
{
    using DCEM.UserCenterService.Main.Application.Repository.Contrac;
    using DCEM.UserCenterService.Main.ViewModel.Request;
    using DCEM.UserCenterService.Main.ViewModel.Response;
    using System.Threading.Tasks;
    using MSLibrary.Xrm;
    using System.Xml.Linq;
    using System;

    public interface IQuestionRepository
    {
        public XDocument QueryQiestion(string  id);

        public XDocument QueryDetailList(Guid id);


        public XDocument QueryAnswersList(Guid id);

        XDocument QueryDeliverychannel(string code);

        XDocument QueryUser(string code);

        XDocument GetOnlylead(string mcs_userid);
    }
}
