//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.Application.Repository.Contrac
{
    using DCEM.UserCenterService.Main.Application.Repository.Contrac;
    using DCEM.UserCenterService.Main.ViewModel.Request;
    using DCEM.UserCenterService.Main.ViewModel.Response;
    using System.Threading.Tasks;
    using MSLibrary.Xrm;
    using System;

    public interface ISmallBookingRepository
    {
        /// <summary>
        /// 查询小订活动
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        string QuerySmallBooking(SmallBookingListRequest request);
        /// <summary>
        /// 查询小订活动对应的权益包
        /// </summary>
        /// <param name="samllbookingid"></param>
        /// <returns></returns>
        string QueryEquityPackage(Guid samllbookingid);
        /// <summary>
        /// 查询权益包对应的权益项
        /// </summary>
        /// <param name="filterequitypackageids"></param>
        /// <returns></returns>
        string QueryEquity(Guid filterequitypackageids);
        /// <summary>
        /// 查询小订活动对应的选配
        /// </summary>
        /// <param name="samllbookingid"></param>
        /// <returns></returns>
        string QueryOptional(Guid samllbookingid);
        /// <summary>
        /// 查询小订活动图片
        /// </summary>
        /// <param name="samllbookingid"></param>
        /// <returns></returns>
        string QueryBookingImage(Guid samllbookingid);
    }
}
