//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.Application.Repository.Contrac
{
    using DCEM.UserCenterService.Main.Application.Repository.Contrac;
    using DCEM.UserCenterService.Main.ViewModel.Request;
    using DCEM.UserCenterService.Main.ViewModel.Response;
    using System.Threading.Tasks;
    using MSLibrary.Xrm;
    using System;

    public interface ISmallBookingRepository
    {
        /// <summary>
        /// 查询小订活动
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        string QuerySmallBooking(SmallBookingListRequest request);
        /// <summary>
        /// 查询小订活动对应的权益包
        /// </summary>
        /// <param name="samllbookingid"></param>
        /// <returns></returns>
        string QueryEquityPackage(Guid samllbookingid);
        /// <summary>
        /// 查询权益包对应的权益项
        /// </summary>
        /// <param name="filterequitypackageids"></param>
        /// <returns></returns>
        string QueryEquity(Guid filterequitypackageids);
        /// <summary>
        /// 查询小订活动对应的选配
        /// </summary>
        /// <param name="samllbookingid"></param>
        /// <returns></returns>
        string QueryOptional(Guid samllbookingid);
        /// <summary>
        /// 查询小订活动图片
        /// </summary>
        /// <param name="samllbookingid"></param>
        /// <returns></returns>
        string QueryBookingImage(Guid samllbookingid);
        /// <summary>
        /// 查询选配图片
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        string QueryOptionalImage(Guid id);
        /// <summary>
        /// 查询预约号
        /// </summary>
        /// <param name="blindOrder"></param>
        /// <returns></returns>
        string QueryBlindOrder(string blindOrder);
        /// <summary>
        /// 查询唯一线索
        /// </summary>
        /// <param name="onlyleadid"></param>
        /// <returns></returns>
        string QueryOnlyLead(string onlyleadid);
        /// <summary>
        /// 查询推荐人
        /// </summary>
        /// <param name="spare4"></param>
        /// <returns></returns>
        string QueryOnlyLeadByUserId(string userid);
        /// <summary>
        /// 查询厅店
        /// </summary>
        /// <param name="dealerid"></param>
        /// <returns></returns>
        string GetDealerById(string dealerid);
        /// <summary>
        /// 查询小订订单
        /// </summary>
        /// <param name="orderCode"></param>
        /// <returns></returns>
        string QuerySmallOrder(string orderCode);
        /// <summary>
        /// 查询是否存在销售机会
        /// </summary>
        /// <param name="onlyleadid"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        string QueryAccount(string onlyleadid, Guid dealerid);
        /// <summary>
        /// 查询是否存在销售机会
        /// </summary>
        /// <param name="onlyleadid"></param>
        /// <returns></returns>
        string QueryAccountMater(string onlyleadid);
    }
}
