//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.Application.Repository
{
    using DCEM.UserCenterService.Main.Application.Repository.Contrac;
    using DCEM.UserCenterService.Main.ViewModel.Request;
    using DCEM.UserCenterService.Main.ViewModel.Response;
    using System.Threading.Tasks;
    using MSLibrary.Xrm;


    public class BlindOrderRepository : IBlindOrderRepository
    {
        /// <summary>
        /// 查询预约号列表，根据预约号倒序查询（排序无改）
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public string QueryList(BlindOrderListRequest request)
        {
            var filter = string.Empty;
            if (!string.IsNullOrWhiteSpace(request.mcs_mobilephone))
            {
                filter += $"<condition attribute='mcs_mobilephone' operator='eq' value='{request.mcs_mobilephone}' />";
            }
            if (request.mcs_premiumcodestatus!=null)
            {
                filter += $"<condition attribute='mcs_premiumcodestatus' operator='eq' value='{request.mcs_premiumcodestatus}' />";
            }
            var fetchString = $@"<fetch version='1.0' count='{request.PageSize}' page='{request.PageIndex}' output-format='xml-platform' mapping='logical' distinct='false'>
                  <entity name='mcs_blindorder'>
                    <attribute name='mcs_name' />
                    <attribute name='createdon' />
                    <attribute name='mcs_ordertime' />
                    <attribute name='mcs_mobilephone' />
                    <attribute name='mcs_fullname' />
                    <attribute name='mcs_description' />
                    <attribute name='mcs_exteriorcolor' />
                    <attribute name='mcs_interiorcolor' />
                    <attribute name='mcs_campaignid' />
                    <attribute name='mcs_usecarcity' />
                    <attribute name='mcs_vehtype' />
                    <attribute name='modifiedon' />
                    <attribute name='mcs_premiumcode' />
                    <attribute name='mcs_blindorderid' />
                    <order attribute='mcs_premiumcode' descending='true' />
                    <filter type='and'>
                      <condition attribute='statecode' operator='eq' value='0' />
                      <condition attribute='mcs_premiumcode' operator='not-null' />
                      {filter}
                    </filter>
                  </entity>
                </fetch>";

            return fetchString;
        }
    }
}
