//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.Application.Repository
{
    using DCEM.UserCenterService.Main.Application.Repository.Contrac;
    using DCEM.UserCenterService.Main.ViewModel.Request;
    using DCEM.UserCenterService.Main.ViewModel.Response;
    using System.Threading.Tasks;
    using MSLibrary.Xrm;
    using System.Xml.Linq;
    using System;

    public class CampaignonlineregRepository : ICampaignonlineregRepository
    {

        public XDocument QueryList(CampaignonlineregListRequest request)
        {
            var filter = string.Empty;
            var fetchXml = $@"<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'
                   count='{request.PageSize}' page='{request.PageIndex}'>
    <entity name='mcs_campaignonlinereg'>
                    <all-attributes />
                    <order attribute='createdon' descending='false' /> 
                    <link-entity name='contact' from='contactid' to='mcs_contactid' link-type='inner' alias='aa'> 
                        <filter type='and'>
                        <condition attribute='mcs_userid' operator='eq' value='{request.UserId}' />
                        </filter>
                    </link-entity>
                    <link-entity name='campaign' from='campaignid' to='mcs_campaignid' link-type='inner' alias='bb'>
                    <all-attributes/>
                    </link-entity>
                  </entity>
                </fetch>";
            return XDocument.Parse(fetchXml);
        }

        public XDocument QueryDetail(Guid id)
        {
            var filter = string.Empty;
            var fetchXml = $@"<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'>
                            <entity name='mcs_campaignonlinereg'>
                                <all-attributes />
                                <order attribute='createdon' descending='false' /> 
                                    <filter type='and'>
                                    <condition attribute='mcs_campaignonlineregid' operator='eq' value='{id}' />
                                    </filter>
                                <link-entity name='campaign' from='campaignid' to='mcs_campaignid' link-type='inner' alias='bb'>
                                <all-attributes/>
                                </link-entity>
                                </entity>
                            </fetch>";
            return XDocument.Parse(fetchXml);
        }
    }
}
