//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.Application.Repository
{
    using DCEM.UserCenterService.Main.Application.Repository.Contrac;
    using DCEM.UserCenterService.Main.ViewModel.Request;
    using DCEM.UserCenterService.Main.ViewModel.Response;
    using System.Threading.Tasks;
    using MSLibrary.Xrm;
    using System.Xml.Linq;
    using System;

    public class QuestionRepository : IQuestionRepository
    {

        /// <summary>
        /// 问卷设定
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public XDocument QueryQiestion(Guid id)
        {
            var filter = string.Empty;
            var fetchXml = $@"<fetch version='1.0'   output-format='xml-platform' mapping='logical' distinct='false'>
                    <entity name='mcs_questionnairesetting'>
                    <all-attributes />
                    <order attribute='createdon' descending='false' />
                    <filter type='and'>
                      <condition attribute='statecode' operator='eq' value='0' /> 
                      <condition attribute='mcs_questionnairesettingid' operator='eq' value='{id}' />
                    </filter>
                  </entity>
                </fetch>"; 
            return XDocument.Parse(fetchXml);
        }


        /// <summary>
        /// 问题库
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public XDocument QueryDetailList(Guid id)
        {
            var filter = string.Empty;
            var fetchXml = $@"<fetch version='1.0'   output-format='xml-platform' mapping='logical' distinct='false'>
                    <entity name='mcs_questions'>
                    <all-attributes />
                    <order attribute='mcs_type' descending='false' />
                    <order attribute='mcs_questioncode' descending='false' />
                    <filter type='and'>
                      <condition attribute='statecode' operator='eq' value='0' />  
                    </filter>
                    <link-entity name='mcs_questionnairedetail' from='mcs_questions' to='mcs_questionsid' link-type='inner' alias='ae'>
                          <filter type='and'>
                              <condition attribute='mcs_questionnairesetting' operator='eq' value='{id}' /> 
                           </filter> 
                    </link-entity>
                  </entity>
                </fetch>";
            return XDocument.Parse(fetchXml);
        }


        /// <summary>
        /// 问题库问题项获取
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public XDocument QueryAnswersList(Guid id)
        {
            var filter = string.Empty;
            var fetchXml = $@"<fetch version='1.0'   output-format='xml-platform' mapping='logical' distinct='false'>
                    <entity name='mcs_answers'>
                    <all-attributes />
                    <order attribute='createdon' descending='false' />
                    <filter type='and'>
                      <condition attribute='statecode' operator='eq' value='0' />  
                    </filter>
                    <link-entity name='mcs_questionanswer' from='mcs_answercode' to='mcs_answersid' link-type='inner' alias='a'>
                        <link-entity name='mcs_questions' from='mcs_questionsid' to='mcs_questioncode' link-type='inner' alias='b'>

                             <attribute name='mcs_questionsid' alias='questionsid' />                            
                             <link-entity name='mcs_questionnairedetail' from='mcs_questions' to='mcs_questionsid' link-type='inner' alias='c'>
                              <filter type='and'>
                                <condition attribute='mcs_questionnairesetting' operator='eq' value='{id}' /> 
                               </filter> 
                            </link-entity>
                        </link-entity>
                    </link-entity>
                  </entity>
                </fetch>";
            return XDocument.Parse(fetchXml);
        }



    }
}
