//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.Application.Repository
{
    using DCEM.UserCenterService.Main.Application.Repository.Contrac;
    using DCEM.UserCenterService.Main.ViewModel.Request;
    using DCEM.UserCenterService.Main.ViewModel.Response;
    using System.Threading.Tasks;
    using MSLibrary.Xrm;
    using System;
    using System.Xml.Linq;

    public class ShippingaddressRepository : IShippingaddressRepository
    {


        public XDocument QueryList(ShippingaddressListRequest request)
        {
            var filter = string.Empty; 
            var fetchXml = $@"<fetch version='1.0' count='{request.PageSize}' page='{request.PageIndex}' output-format='xml-platform' mapping='logical' distinct='false'>
                    <entity name='mcs_shippingaddress'>
                    <all-attributes />
                    <order attribute='createdon' descending='false' />
                    <filter type='and'>
                      <condition attribute='statecode' operator='eq' value='0' /> 
                      <condition attribute='mcs_userid' operator='eq' value='{request.mcs_userid}' />
                    </filter>
                  </entity>
                </fetch>";

            return XDocument.Parse(fetchXml);
        }


        public   XDocument  QueryDetail( Guid id)
        {
            var filter = string.Empty;
            var fetchXml = $@"<fetch version='1.0'   output-format='xml-platform' mapping='logical' distinct='false'>
                    <entity name='mcs_shippingaddress'>
                    <all-attributes />
                    <order attribute='createdon' descending='false' />
                    <filter type='and'>
                      <condition attribute='statecode' operator='eq' value='0' /> 
                      <condition attribute='mcs_shippingaddressid' operator='eq' value='{id}' />
                    </filter>
                  </entity>
                </fetch>";

            return XDocument.Parse(fetchXml);
        }
    }
}
