//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.Application.Repository
{
    using DCEM.UserCenterService.Main.Application.Repository.Contrac;
    using DCEM.UserCenterService.Main.ViewModel.Request;
    using DCEM.UserCenterService.Main.ViewModel.Response;
    using System.Threading.Tasks;
    using MSLibrary.Xrm;
    using System;

    public class SmallBookingRepository : ISmallBookingRepository
    {
        /// <summary>
        /// 查询小订活动关联图片
        /// </summary>
        /// <param name="samllbookingid"></param>
        /// <returns></returns>
        public string QueryBookingImage(Guid samllbookingid)
        {
            var strFetch = $@"<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'>
              <entity name='mcs_tc_productimage'>
                <attribute name='mcs_imagetype' />
                <attribute name='mcs_imagename' />
                <attribute name='mcs_imageindex' />
                <attribute name='mcs_tc_productimageid' />
                <attribute name='mcs_smallbooking' />
                <order attribute='mcs_imagetype' descending='false' />
                <order attribute='mcs_imageindex' descending='false' />
                <filter type='and'>
                  <condition attribute='statecode' operator='eq' value='0' />
                  <condition attribute='mcs_smallbooking' operator='eq'  value='{samllbookingid}' />
                </filter>
              </entity>
            </fetch>";

            return strFetch;
        }

        /// <summary>
        /// 查询小订活动关联的权益项
        /// </summary>
        /// <param name="filterequitypackageid"></param>
        /// <returns></returns>
        public string QueryEquity(Guid filterequitypackageid)
        {
            var strFetch = $@"<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='true'>
                <entity name='mcs_equity'>
                <attribute name='mcs_name' />
                <attribute name='createdon' />
                <attribute name='mcs_description' />
                <attribute name='mcs_code' />
                <attribute name='mcs_sort' />
                <attribute name='mcs_equityid' />
                <order attribute='mcs_sort' descending='true' />
                <filter type='and'>
                  <condition attribute='statecode' operator='eq' value='0' />
                </filter>
                <link-entity name='mcs_mcs_equity_mcs_equitypackage' from='mcs_equityid' to='mcs_equityid' visible='false' intersect='true'>
                  <link-entity name='mcs_equitypackage' from='mcs_equitypackageid' to='mcs_equitypackageid' alias='ep'>
                    <filter type='and'>
                      <condition attribute='mcs_equitypackageid' operator='eq'  value='{filterequitypackageid}' />
                    </filter>
                  </link-entity>
                </link-entity>
              </entity>
            </fetch>";

            return strFetch;
        }

        /// <summary>
        /// 查询小订活动关联的权益包
        /// </summary>
        /// <param name="samllbookingid"></param>
        /// <returns></returns>
        public string QueryEquityPackage(Guid samllbookingid)
        {
            var strFetch = $@"<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='true'>
               <entity name='mcs_equitypackage'>
                <attribute name='mcs_name' />
                <attribute name='createdon' />
                <attribute name='mcs_description' />
                <attribute name='mcs_code' />
                <attribute name='mcs_equitypackageid' />
                <order attribute='mcs_code' descending='false' />
                <filter type='and'>
                  <condition attribute='statecode' operator='eq' value='0' />
                </filter>
                <link-entity name='mcs_mcs_equitypackage_mcs_smallbooking' from='mcs_equitypackageid' to='mcs_equitypackageid' visible='false' intersect='true'>
                  <link-entity name='mcs_smallbooking' from='mcs_smallbookingid' to='mcs_smallbookingid' alias='af'>
                    <filter type='and'>
                      <condition attribute='mcs_smallbookingid' operator='eq' value='{samllbookingid}' />
                    </filter>
                  </link-entity>
                </link-entity>
              </entity>
            </fetch>";

            return strFetch;

        }

        /// <summary>
        /// 小订活动选配
        /// </summary>
        /// <param name="samllbookingid"></param>
        /// <returns></returns>
        public string QueryOptional(Guid samllbookingid)
        {
            var strFetch = $@"<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='true'>
              <entity name='mcs_optional'>
                <attribute name='mcs_optionalid' />
                <attribute name='mcs_name' />
                <attribute name='mcs_limitedtimeprice' />
                <attribute name='mcs_description' />
                <attribute name='mcs_code' />
                <attribute name='mcs_originalprice' />
                <order attribute='mcs_name' descending='false' />
                <filter type='and'>
                  <condition attribute='statecode' operator='eq' value='0' />
                </filter>
                <link-entity name='mcs_mcs_optional_mcs_smallbooking' from='mcs_optionalid' to='mcs_optionalid' visible='false' intersect='true'>
                  <link-entity name='mcs_smallbooking' from='mcs_smallbookingid' to='mcs_smallbookingid' alias='af'>
                    <filter type='and'>
                      <condition attribute='mcs_smallbookingid' operator='eq' value='{samllbookingid}' />
                    </filter>
                  </link-entity>
                </link-entity>
              </entity>
            </fetch>";

            return strFetch;
        }

        /// <summary>
        /// 查询选配图片
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public string QueryOptionalImage(Guid optionalid)
        {
            var strFetch = $@"<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'>
              <entity name='mcs_tc_productimage'>
                <attribute name='mcs_imagetype' />
                <attribute name='mcs_imagename' />
                <attribute name='mcs_imageindex' />
                <attribute name='mcs_tc_productimageid' />
                <attribute name='mcs_optionalimage' />
                <order attribute='mcs_imagetype' descending='false' />
                <order attribute='mcs_imageindex' descending='false' />
                <filter type='and'>
                  <condition attribute='statecode' operator='eq' value='0' />
                  <condition attribute='mcs_optionalimage' operator='eq'  value='{optionalid}' />
                </filter>
              </entity>
            </fetch>";

            return strFetch;
        }

        /// <summary>
        /// 查询小订活动
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public string QuerySmallBooking(SmallBookingListRequest request)
        {
            var filter = string.Empty;
            if (request.mcs_starttime!=null)
            {
                filter += $"<condition attribute='mcs_starttime' operator='ge' value='{request.mcs_starttime}' />";
            }
            if (request.mcs_endtime != null)
            {
                filter += $"<condition attribute='mcs_endtime' operator='le' value='{request.mcs_endtime}' />";
            }
            if (request.mcs_poststatus != null)
            {
                filter += $"<condition attribute='mcs_poststatus' operator='eq' value='{request.mcs_poststatus}' />";
            }
            var fetchString = $@"<fetch version='1.0' count='{request.PageSize}' page='{request.PageIndex}' output-format='xml-platform' mapping='logical' distinct='false'>
                  <entity name='mcs_smallbooking'>
                    <attribute name='mcs_name' />
                    <attribute name='createdon' />
                    <filter type='and'>
                      <condition attribute='statecode' operator='eq' value='0' />
                      {filter}
                    </filter>
                  </entity>
                </fetch>";

            return fetchString;
        }
    }
}
