//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.Application.Repository
{
    using DCEM.UserCenterService.Main.Application.Repository.Contrac;
    using DCEM.UserCenterService.Main.ViewModel.Request;
    using DCEM.UserCenterService.Main.ViewModel.Response;
    using System.Threading.Tasks;
    using MSLibrary.Xrm;


    public class UserCarInfoRepository : IUserCarInfoRepository
    {
        /// <summary>
        /// 用户车辆列表查询
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public string QueryList(UserCarInfoListRequest request)
        {
            var filter = string.Empty;
            if (!string.IsNullOrWhiteSpace(request.mcs_carinfoid))
            {
                filter += $"<condition attribute='mcs_carinfoid' operator='eq' value='{request.mcs_carinfoid}' />";
            }
            if (!string.IsNullOrWhiteSpace(request.mcs_username))
            {
                filter += $"<condition attribute='mcs_username' operator='eq' value='{request.mcs_username}' />";
            }
            if (!string.IsNullOrWhiteSpace(request.mcs_phone))
            {
                filter += $"<condition attribute='mcs_phone' operator='eq' value='{request.mcs_phone}' />";
            }
            if (!string.IsNullOrWhiteSpace(request.mcs_plate))
            {
                filter += $"<condition attribute='mcs_plate' operator='eq' value='{request.mcs_plate}' />";
            }
            if (!string.IsNullOrWhiteSpace(request.mcs_userid))
            {
                filter += $"<condition attribute='mcs_userid' operator='eq' value='{request.mcs_userid}' />";
            }
            var fetchString = $@"<fetch version='1.0' count='{request.PageSize}' page='{request.PageIndex}' output-format='xml-platform' mapping='logical' distinct='false'>
                    <entity name='mcs_usercarinfo'>
                    <all-attributes />
                    <order attribute='createdon' descending='false' />
                    <link-entity name='mcs_vehowner' from='mcs_vehownerid' to='mcs_carinfoid' link-type='inner' alias='bb'>
                      <all-attributes/>
                    </link-entity>
                    <link-entity name='mcs_carmodel' from='mcs_carmodelid' to='mcs_model' link-type='inner' alias='cc'>
                       <attribute name='mcs_name' />
                    </link-entity>
                    <filter type='and'>
                      <condition attribute='statecode' operator='eq' value='0' />
                      {filter}
                    </filter>
                  </entity>
                </fetch>";

            return fetchString;
        }
    }
}
