//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.Application.Repository
{
    using DCEM.UserCenterService.Main.Application.Repository.Contrac;
    using DCEM.UserCenterService.Main.ViewModel.Request;
    using DCEM.UserCenterService.Main.ViewModel.Response;
    using System.Threading.Tasks;
    using MSLibrary.Xrm;
    using System.Xml.Linq;

    public class UsermessageRepository : IUsermessageRepository
    {
        public async Task<XDocument> GetMes(UsermessageRequest request)
        {
            return await Task<XDocument>.Run(() =>
            {

                var fetchXml = $@"<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='true'>
  <entity name='mcs_usermessage'>
    <attribute name='mcs_name' /> 
    <attribute name='createdon' /> 
    <order attribute='createdon' descending='true' />
    <filter type='and'>
      <condition attribute='mcs_type' operator='eq' value='{request.type}' />
      <condition attribute='mcs_phone' operator='eq' value='{request.phone}' />
    </filter> 
  </entity>
</fetch>";
                return XDocument.Parse(fetchXml);
            });
        }

 
    }
}
