//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.ViewModel.Response
{
    using System.Collections.Generic;
    using MSLibrary.Xrm;
    
    /// <summary>
    /// 内容列表
    /// </summary>
    public class ContentListResponse : PageBaseResponseModel
    {
        public List<CrmEntity> ContentList { get; set; }

        //缩略图的前置绝对路径
        public string PicPathPre { get; set; }

        public string ErrorMessage { get; set; }
    }

    /// <summary>
    /// 内容详情
    /// </summary>
    public class ContentDetailResponse
    {
        public CrmEntity Content { get; set; }

        //缩略图的前置绝对路径
        public string PicPathPre { get; set; }

        public string ErrorMessage { get; set; }
    }

    /// <summary>
    /// 内容生成的html页面
    /// </summary>
    public class ContentPageResponse
    {
        public bool IsSuccess { get; set; } = true;
        public string Url { get; set; }
    }
}
