//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.ViewModel.Response
{
    using System.Collections.Generic;
    using MSLibrary.Xrm;
    using Newtonsoft.Json.Linq;

    public class SmallBookingListResponse : PageBaseResponseModel
    {
        public SmallBookingListResponse()
        {
            SmallBookingList = new List<SmallBooking>();
        }

        public List<SmallBooking> SmallBookingList { get; set; }
    }

    public class SmallBooking
    {
        public SmallBooking()
        {
            SmallBookingInfo = new JObject();
            BookingImageArray = new JArray();
            EquityPackageArray = new List<EquityPackage>();//new JArray();
            OptionalArray = new List<Optional>();
        }
        /// <summary>
        /// 小订活动实体
        /// </summary>
        public JObject SmallBookingInfo { get; set; }
        /// <summary>
        /// 小订实体图片
        /// </summary>
        public JArray BookingImageArray { get; set; }
        /// <summary>
        /// 小订权益包
        /// </summary>
        public List<EquityPackage> EquityPackageArray { get; set; }
        /// <summary>
        /// 小订选配
        /// </summary>
        public List<Optional> OptionalArray { get; set; }
    }

    /// <summary>
    /// 小订权益包
    /// </summary>
    public class EquityPackage
    {
        public EquityPackage()
        {
            EquityPackageInfo = new JObject();
            EquityArray = new JArray();
        }
        public JObject EquityPackageInfo { get; set; }
        /// <summary>
        /// 小订权益项
        /// </summary>
        public JArray EquityArray { get; set; }
    }

    /// <summary>
    /// 小订选配
    /// </summary>
    public class Optional 
    {
        public Optional() 
        {
            OptionalInfo= new JObject();
            OptionalImageArray= new JArray();
        }
        public JObject OptionalInfo { get; set; }
        /// <summary>
        /// 小订选配图片
        /// </summary>
        public JArray OptionalImageArray { get; set; }
    }


}
