//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.ViewModel.Response
{
    using System.Collections.Generic;
    using MSLibrary.Xrm;
    using Newtonsoft.Json.Linq;

    public class SmallBookingListResponse : PageBaseResponseModel
    {
        public SmallBookingListResponse()
        {
            SmallBookingList = new List<SmallBooking>();
        }

        public List<SmallBooking> SmallBookingList { get; set; }
    }

    public class SmallBooking
    {
        public SmallBooking()
        {
            SmallBookingInfo = new JObject();
            ProductImageArray = new JArray();
            EquityPackageArray = new JArray(new List<EquityPackageListResponse>());//new JArray();
            OptionalArray = new JArray();
        }
        /// <summary>
        /// 小订活动实体
        /// </summary>
        public JObject SmallBookingInfo { get; set; }
        /// <summary>
        /// 小订实体图片
        /// </summary>
        public JArray ProductImageArray { get; set; }
        /// <summary>
        /// 小订权益包
        /// </summary>
        public JArray EquityPackageArray { get; set; }
        /// <summary>
        /// 小订选配
        /// </summary>
        public JArray OptionalArray { get; set; }

    }
    /// <summary>
    /// 小订权益包
    /// </summary>
    public class EquityPackageListResponse
    {
        public EquityPackageListResponse()
        {
            EquityPackageList = new List<CrmEntity>();
        }

        public List<CrmEntity> EquityPackageList { get; set; }
    }
    /// <summary>
    /// 小订权益项
    /// </summary>
    //public class Equities
    //{
    //    //public Equities()
    //    //{
    //    //    Equity = new CrmEntity();
    //    //}
    //    public CrmEntity Equity { get; set; }
    //}
}
