//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.UserCenterService.Main.Factory
{
    using DCEM.UserCenterService.Main.Application.App;
    using DCEM.UserCenterService.Main.Application.App.Contrac;
    using DCEM.UserCenterService.Main.Application.Repository;
    using DCEM.UserCenterService.Main.Application.Repository.Contrac;
    using DCEM.UserCenterService.Main.Application.Services;
    using DCEM.UserCenterService.Main.Application.Services.Contrac;
    using System.Threading.Tasks;
    using MSLibrary.Xrm;
    using MSLibrary;
    using System;
    
    
    public class UserFactory : IFactory<Task<IAppUser>>
    {
        
        public virtual Task<IAppUser> Create()
        {
            var crmService = StartupHelper.CreateCrmService();
            IUserRepository userrepository = new UserRepository();
            IUserService userservice = new UserService(crmService, userrepository);
            IUserNoticeRepository userNoticerepository = new UserNoticeRepository();
            IUserNoticeService userNoticeservice = new UserNoticeService(crmService, userNoticerepository);
            IAppUser app = new AppUser(userservice, userNoticeservice);
            return Task.FromResult(app); ;
        }
    }
}
