//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCEM.SalesAssistant.Main.Factory
{
    using DCEM.SalesAssistant.Main.Application.App;
    using DCEM.SalesAssistant.Main.Application.App.Contrac;
    using DCEM.SalesAssistant.Main.Application.Repository;
    using DCEM.SalesAssistant.Main.Application.Repository.Contrac;
    using DCEM.SalesAssistant.Main.Application.Services;
    using DCEM.SalesAssistant.Main.Application.Services.Contrac;
    using System.Threading.Tasks;
    using MSLibrary.Xrm;
    using MSLibrary;
    using System;
    
    
    public class InvoiceFactory : IFactory<Task<IAppInvoice>>
    {
        
        public virtual Task<IAppInvoice> Create()
        {
            var crmService = StartupHelper.CreateCrmService();
                IInvoiceRepository invoicerepository = new InvoiceRepository();
                IInvoiceService invoiceservice = new InvoiceService(crmService, invoicerepository);
                IAppInvoice app = new AppInvoice(invoiceservice); 
                return Task.FromResult(app);;
        }
    }
}
